### ISSUE TITLE
Don't recommend balena etcher (includes spyware/adware) for writing/verify images

### ISSUE THREAD

**Issue by rradar** [armbian/documentation#66]
As balena etcher is growing fat (>400Mb) and ugly (includes tracking, analytics, ads - or "promotend content" the authors like to call it) these days it would be a good move to suggest the users a proper lightweight alternative which does the work without spying and ads.

Their is various FOSS software out their which does exactly the same etcher does (writing and verify). One of them (available for Windows, MacOSX and Linux) is the less than 300Kb small [usbimager](https://gitlab.com/bztsrc/usbimager)

> ![image](https://user-images.githubusercontent.com/34582688/77207906-76717b80-6af2-11ea-8162-58c4c5003f19.png)
> _https://gitlab.com/bztsrc/usbimager#comparition_

Etcher is linked on the **website** ('SD writing tool', faq-section: How to start) and mentioned in the **docs**:
- https://docs.armbian.com/User-Guide_Getting-Started/#how-to-prepare-a-sd-card
- https://docs.armbian.com/User-Guide_Getting-Started-Download-Page/

It could serve as a good example for others: https://github.com/OpenMediaVault-Plugin-Developers/docs/issues/9

**Comment by igorpecovnik** [comment]
I agree with you and I do hate bloat / spy ware ... and support you, but we need common agree on this. SD write verifying is for us a very important part - it has to be enabled by default. Without, there is no way to even think about change. On the other hand, we don't have time to deal with SD write tooling ... which is why Etcher was chosen. Let's see for other opinions.

BTW. I already throw out Etcher from our build system https://github.com/armbian/build/pull/1522

**Comment by tido-** [comment]
In the begin there was version of Etcher that had problems. So, I didn't upgrade. I am still running Etcher 1.2.1 on my Ubuntu Mate 18.04, works like a charm (80 Mb)

**Comment by tido-** [comment]
I created a topic here: https://forum.armbian.com/topic/13421-need-your-help-what-else-beside-etcher/

**Comment by rradar** [comment]
I guess another reason for less SDcard troubles (beside doing the mandatory verify) is also the improved build quality and affordable prices today. A couple of years ago you could buy cheap only with low quality and good cards costed double, tripple or more than the basic ones. Today you just buy cheap and get quality cards rated A-something - no need to pay more for that anymore. But in all verifying should be done anyways. If someone fails repeatingly verifying a written image it's a good thing to try [f3](http://oss.digirati.com.br/f3/) - in the best case it can fix partly broken flash storage.

**Comment by igorpecovnik** [comment]
> since Etcher the forum is almost empty of SDcard troubles.

Verifying is the essential and also SD cards got much better indeed. But they still do break ... while I am a heavy user.

IMO we can change recommendation, which will anyway not steer people away from Etcher. That takes much longer ...  let's just wait for some feedback and if we can push towards that verify is default enabled? I don't want to compile our version because of that.

**Comment by rradar** [comment]
> we can push towards that verify is default enabled

> if **more users are asking** for this, I'll made "verify" checked by default.
> _https://gitlab.com/bztsrc/usbimager/-/issues/5_

Looks like **we** can :tada:

**Comment by rradar** [comment]
Their is [no 7-zip support](https://gitlab.com/bztsrc/usbimager/-/issues/7) in usbimager and it's not planned because it's 
> very very very (very) badly documented

and 
> totally non-portable

the [maintainer](https://gitlab.com/bztsrc) of usbimager states [here](https://gitlab.com/bztsrc/usbimager/-/issues/7#note_309094322)

> FYI, I'd recommend against using 7-Zip and xz. They might be smaller than other formats, but they suffer from serious design flaws which makes them inappropriate for long term archiving, and makes them highly vulnerable to transmission errors. One single bit error can render the file uncompressable and you can throw the entire archive out of the window. Read more: https://www.nongnu.org/lzip/xz_inadequate.html


If armbian wants to go with usbimager in the future it looks like the type of archive needs to be changed.

**Comment by kriston** [comment]
How about Raspberry Pi Imager? 

https://www.raspberrypi.org/blog/raspberry-pi-imager-imaging-utility/

On 2020-03-22 08:05, rradar wrote:

> Reopened #66 [1]. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/armbian/documentation/issues/66
[2] https://github.com/armbian/documentation/issues/66#event-3152598241
[3]

**Comment by igorpecovnik** [comment]
> How about Raspberry Pi Imager?

Can we build it automatically / when needed?

**Comment by kriston** [comment]
Looks like we can here: 

https://github.com/raspberrypi/rpi-imager

On 2020-03-22 12:27, Igor Pečovnik wrote:

>> How about Raspberry Pi Imager?
> 
> Can we build it automatically / when needed? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/armbian/documentation/issues/66#issuecomment-602235108
[2]

**Comment by igorpecovnik** [comment]
Yes, I saw this. This only means its opensource :)

We need a maintainer, a person that will setup Jenkins job and rebuild at will / when needed / when upstream will be build ... with our patches.

**Comment by rradar** [comment]
I think to stay with something existing and not forking and maintaining a new thing saves valuable time for the core project of armbian.

Is the change of the archive type (to one usbimager already supports) something armbian could agree on or is this out of reach?

> That being said I'm not against of supporting 7z in USBImager, just need a good doc or a minimal portable lib. So far I was unable to find any.
> Btw, USBImager uses the first file in the archive, so if it's the .img, then armbian 7z will work too.

the maintainer of [usbimager](https://gitlab.com/bztsrc/usbimager/-/issues/7#note_309173669)

**Comment by igorpecovnik** [comment]
> Is the change of the archive type (to one usbimager already supports) something armbian could agree on or is this out of reach?

Anything in this regard is a long term change. We had lots of discussion on this in the past.

> I think to stay with something existing and not forking and maintaining a new thing saves valuable time for the core project of armbian.

If someone that currently does not do something around armbian, this is not a problem. I will certainly not touch it - I barely find time to read/respond here. It also require not typical skills needed for our main objectives which is also good.

TL;DR;
If we have verify default on, next problem is how to provide pgp signatures and SHA checks? .gz is a single file compressor.

https://armbian.atlassian.net/browse/AR-185

**Comment by rradar** [comment]
> If we have verify default on

USBImager in Version 1.0.1 was just released and includes verify on by default :tada: 

> next problem is how to provide pgp signatures and SHA checks? .gz is a single file compressor.

Die etcher included such a functionality to check the signatures/checksums of the archive or image file?

**Comment by shoka555** [comment]
I've built and installed rpi-imager on my Linux Mint laptop.
It builds painlessly and creates an output .deb file.
Installing that deb adds a new application to the Mint menu structure nicely.

That side of the project is excellent.

However it seems to be focused on fetching images from the net, rather than allowing selection of image files  on the local system. The git page suggests parameters to feed the binary to use a local repository, but that does not seem to allow a simple directory search for image files.

As a test I selected the Raspbian lite link it offered, and put an SDcard in the Mint system.

I have no idea where that image came from, presumably the RPi Foundation download site...

Disconcertingly the select SD card button  opens a selection dialog, but having made the selection the button gives no indication that an SD card has been selected. 

Triggering the write behaves as expected, with a progress bar that changes colour when the operation goes from writing to verifying the image.

When verification completes, it provides  a message saying the SDcard can be removed, and when that is acknowledged, exits.

I will continue with etcher, at least for the moment.

The lack of choice of download method is one limitation, I usually use torrent downloads, in consideration of upstream's bandwidth.  

The opaqueness of the source of the images offered is disconcerting. 

The lack of facility to verify the image shasum after download but before writing is limiting.

The inefficiency of downloading images every time you write one is also a limitation, I usually verify that my copy of the upstream  image is still current, and only download again if its not.

Also the inability to write more copies of the image in one pass, I often use the facility in etcher to burn more images in one set up. 

Not sure where it is aimed, presumably at absolute beginners with a shiny new Pi and no familiarity with general tools.

Harry

**Comment by tido-** [comment]
> TL;DR;
> If we have verify default on, next problem is how to provide pgp signatures and SHA checks? .gz is a single file compressor.

> Did etcher included such a functionality to check the signatures/checksums of the archive or image file?

Not that I am aware of and it is NOT necessary. If people download with .torrent, it does this check auto-magic-ally.  This is one of the reason, apart for spreading the load, that I always prefer .torrent.

I will soon write the Kubuntu 20.04beta on my memory-stick, but before I do so I will update to the latest .deb from bzt :)

**Comment by igorpecovnik** [comment]
Thank you @shoka555 for this write up!

> Maybe such feature could be included to usbimager also...

If we stay on .gz, which is acceptable, we would need a custom option within USBimager ... if ARMBIAN image is loaded then download file SHA from Armbian server (+ note/link to how you can verify manually if you don't trust usbimager) and run check on a file. If server is unreachable = warning, if sha fails error otherwise burn the image?

**Comment by kriston** [comment]
Scroll down and select "Use custom" to use your own image. 

On 2020-03-23 17:02, Harry Moyes wrote:

> I've built and installed rpi-imager on my Linux Mint laptop.
> It builds painlessly and creates an output .deb file.
> Installing that deb adds a new application to the Mint menu structure nicely. 
> 
> That side of the project is excellent. 
> 
> However it seems to be focused on fetching images from the net, rather than allowing selection of image files on the local system. The git page suggests parameters to feed the binary to use a local repository, but that does not seem to allow a simple directory search for image files. 
> 
> As a test I selected the Raspbian lite link it offered, and put an SDcard in the Mint system. 
> 
> I have no idea where that image came from, presumably the RPi Foundation download site... 
> 
> Disconcertingly the select SD card button opens a selection dialog, but having made the selection the button gives no indication that an SD card has been selected. 
> 
> Triggering the write behaves as expected, with a progress bar that changes colour when the operation goes from writing to verifying the image. 
> 
> When verification completes, it provides a message saying the SDcard can be removed, and when that is acknowledged, exits. 
> 
> I will continue with etcher, at least for the moment. 
> 
> The lack of choice of download method is one limitation, I usually use torrent downloads, in consideration of upstream's bandwidth. 
> 
> The opaqueness of the source of the images offered is disconcerting. 
> 
> The lack of facility to verify the image shasum after download but before writing is limiting. 
> 
> The inefficiency of downloading images every time you write one is also a limitation, I usually verify that my copy of the upstream image is still current, and only download again if its not. 
> 
> Also the inability to write more copies of the image in one pass, I often use the facility in etcher to burn more images in one set up. 
> 
> Not sure where it is aimed, presumably at absolute beginners with a shiny new Pi and no familiarity with general tools. 
> 
> Harry 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/armbian/documentation/issues/66#issuecomment-602854592
[2]

**Comment by shoka555** [comment]
My apologies, I missed that that window was scrollable.
I can indeed select a preprepared image that way.
Not tested it but it correctly recognises an Armbian image file.

H

**Comment by shoka555** [comment]
In my defence the comment on the website

> If the application is started with "--repo [your own URL]" it will use a custom image repository. So can simply create another 'start menu shortcut' to the application with that parameter to use the application with your own images.

led me down a false path, as using that option did not find any image files, for me.

however 

shoka@ShokaLaptop:~$ rpi-imager --help
qt5ct: using qt5ct plugin
rpi-imager [--debug] [--version] [--repo <repository URL>] [<image file to write>]

also looks promising.

H

**Comment by shoka555** [comment]
Testing again, the other "foible" that misled me, is that the drop down menu initially shows no scroll bar, only a selection hand. Click dragging the entries with that selection hand, scrolls the list, and displays a scroll bar thereafter.  Not sure if this is a QT feature, a Cinnamon feature, or deliberate by the developers.

H

**Comment by kriston** [comment]
Yes, the hidden scroll bar is unfortunate.

On 2020-03-24 09:06, Harry Moyes wrote:

> Testing again, the other "foible" that misled me, is that the drop down menu initially shows no scroll bar, only a selection hand. Click dragging the entries with that selection hand, scrolls the list, and displays a scroll bar thereafter. Not sure if this is a QT feature, a Cinnamon feature, or deliberate by the developers. 
> 
> H 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/armbian/documentation/issues/66#issuecomment-603226924
[2]

**Comment by igorpecovnik** [comment]
An opportunity to heat this up: https://forum.armbian.com/topic/13141-armbian-v2005-kagu-planning-thread

**Comment by igorpecovnik** [comment]
.xz format was implemented and next images can be done with it. Links are unchanged, only sha and gpg files were added: https://dl.armbian.com/melea1000/

**Comment by lanefu** [comment]
Documentation now recommends usb-imager first, provides additional description that etcher may contain spyware.

Are we good to close this issue?

**Comment by tido-** [comment]
> Documentation now recommends usb-imager first, provides additional description that etcher may contain spyware.
> 
> Are we good to close this issue?

I guess you didn't read that in the forum
 @OrangePee ,  in regard to you PR, there are two sections to address, if you don't mind:
https://docs.armbian.com/User-Guide_Getting-Started/#how-to-prepare-a-sd-card  
https://docs.armbian.com/User-Guide_Basic-Troubleshooting/#writing-images-to-the-sd-card
